### ISSUE TITLE
NoClassDefFoundError exception when creating PR

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/cloud-client#1]
Using plugin version 1.1, with GATE 8.6-SNAPSHOT build 5dbfc4b, after entering the apiKey, apiPassword and the endpointUrl https://cloud-api.gate.ac.uk/process-document/annie-named-entity-recognizer the following exception is thrown:
```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at uk.ac.gate.cloud.client.RestClient.<init>(RestClient.java:117)
	at uk.ac.gate.cloud.client.RestClient.<init>(RestClient.java:98)
	at uk.ac.gate.cloud.pr.GateCloudPR.init(GateCloudPR.java:200)
	at gate.Factory.createResource(Factory.java:430)
	at gate.gui.NewResourceDialog$4.run(NewResourceDialog.java:270)
	at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at uk.ac.gate.cloud.client.RestClient.<init>(RestClient.java:117)
	at uk.ac.gate.cloud.client.RestClient.<init>(RestClient.java:98)
	at uk.ac.gate.cloud.pr.GateCloudPR.init(GateCloudPR.java:200)
	at gate.Factory.createResource(Factory.java:430)
	at gate.gui.NewResourceDialog$4.run(NewResourceDialog.java:270)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by greenwoodma** [comment]
My guess is you are using java 9 or above where the databind stuff is no longer available by default. Try using java 8 - this is the recommended version still for using gate. I will have a look though as I think I sorted a similar problem elsewhere so it maybe possible to fix this.

**Comment by johann-petrak** [comment]
Hmmm it turns out the exception only occurs when trying to connect to the YODIE-en endpoint, but it all works fine when connecting to the ANNIE endpoint.

**Comment by johann-petrak** [comment]
Yes, this happened using Java 10.0.1.

**Comment by greenwoodma** [comment]
So it's not a bug but expected behaviour. As I said we still recommend java 8 when using gate simply because 9 introduces so many changes some of which break expected behaviour in gate. Some of these we've fixed it worked around, but some we haven't. Essentially if you want gate to work as intended, and not to surprise you with weird error messages, then please use java 8.

**Comment by greenwoodma** [comment]
@johann-petrak if you rebuild the library and the plugin it should now work under Java 9 and above.

**Comment by johann-petrak** [comment]
This did not actually happen because of the endpoint, it only seems to happen when the api key/password is added. 

Yes, I just tested the same fix here, but you beat me with commiting it. Thanks!

**Comment by johann-petrak** [comment]
Turns out it was not the same fix, I added the dependencies to the plugin only. But clearly they should be added to the library. 

However when I compile  5f0b25105af63d6cc3073fe9edea7aadd0909d99 I now get a problem with the gate-cloud-cli: 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.2:shade (default) on project gate-cloud-cli: Error creating shaded jar: Error in ASM processing class META-INF/versions/9/javax/xml/bind/ModuleUtil.class: 55297 -> [Help 1]
```

**Comment by greenwoodma** [comment]
Yes, I said it would work under Java 9 and above, I didn't say you could compile it with anything but Java 8. As I keep saying, if you stick to Java 8 as much as possible all these problems go away.

**Comment by johann-petrak** [comment]
I am getting the same error when compiling with oracle java 1.8.0_172 though.
(I have cleaned to whole maven cache and re-compiled the current gate-core before trying, to make sure there is no java-9 compiled stuff in the cache).

**Comment by greenwoodma** [comment]
Try it now (after a `git pull` obviously)

**Comment by johann-petrak** [comment]
Thanks, upgrading the maven shade plugin fixed this!
