### ISSUE TITLE
Allow calling the service for one or more parts of the document

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/cloud-client#3]
It would be useful if the plugin could have a run-time parameter "containingAnnotationType" which would identify regions of text to annotate by the service. This would allow to annotated very larget documents with slow services (YODIE) without risking a time-out or limiting the processing of a large document to just the parts that are interesting. 
This is probably only possible when sendOnlyText is true.

Not sure how easy this would be with the current approach where the result is obtained in GATE XML format and processed by DocumentStaxUtils.readAnnotationSet - the annotations would need to get the starting offset of the text section added to their offsets in the returned document.

Maybe this could be done with the JSON response format?

**Comment by greenwoodma** [comment]
Or use the segment processing PR as this is exactly the kind of situation it's designed for.

**Comment by johann-petrak** [comment]
True, that is probably the easier solution.
